version: '3'

services:
  app:
    image: aesirxio/dma-app:latest
    pull_policy: always
    environment:
      REACT_APP_SSO_CLIENT_ID: ${REACT_APP_SSO_CLIENT_ID}
      REACT_APP_SSO_CLIENT_SECRET: ${REACT_APP_SSO_CLIENT_SECRET}
      REACT_APP_OPENAI_API_KEY: ${REACT_APP_OPENAI_API_KEY}
    ports:
      - '${PORT-3000}:3000'
